### PR TITLE
headers: added missing DirectWrite defines and interface

### PR DESCRIPTION
**Pull request by mcallegari**
Apparently this is now needed to build Qt 5.7 Windows platform plugin

### CODE REVIEW

**Comment by mcallegari** [comment]
@Alexpux ping ?

**Comment by Alexpux** [comment]
I'm on holidays until 10th May.

**Comment by mcallegari** [comment]
Closing, as duplicate of 390ef6ea3275003c44a404b3bae83455287271ae

**Comment by forgottenswitch** [comment]
https://github.com/Alexpux/mingw-w64/pull/4#issuecomment-262135200

**Pull request closed without merging**
